apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ram
  name: website-moto-preview
  labels:
    app: website-moto-preview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website-moto-preview
  template:
    metadata:
      labels:
        app: website-moto-preview
    spec:
      containers:
      - name: site
        image: "ghcr.io/revidian-moto/moto.revidian.com:latest"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: ram
  name: website-moto-preview
  labels:
    app: website-moto-preview
spec:
  type: ClusterIP
  selector:
    app: website-moto-preview
  ports:
    - protocol: TCP
      name: http
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: ram
  name: website-moto-preview
  labels:
    app: website-moto-preview
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - preview.moto.revidian.com
    secretName: website-moto-preview-tls
  rules:
  - host: preview.moto.revidian.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: website-moto-preview
            port:
              number: 80
