apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ram
  name: moto-website-production
  labels:
    app: moto-website-production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: moto-website-production
  template:
    metadata:
      labels:
        app: moto-website-production
    spec:
      containers:
      - name: site
        image: "ghcr.io/revidian-moto/moto.revidian.com:latest"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: ram
  name: moto-website-production
  labels:
    app: moto-website-production
spec:
  type: ClusterIP
  selector:
    app: moto-website-production
  ports:
    - protocol: TCP
      name: http
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: ram
  name: moto-website-production
  labels:
    app: moto-website-production
spec:
  ingressClassName: caddy
  rules:
  - host: moto.revidian.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: moto-website-production
            port:
              number: 80
  - host: www.moto.revidian.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: moto-website-production
            port:
              number: 80
